{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# EXCEPTION HANDLING"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# In any programming language there are 2 types of errors are possible.\n",
    "\n",
    "==================================================================================================================\n",
    "1) Syntax Errors\n",
    "2) Runtime Errors"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 1.) Syntax Errors:\n",
    "\n",
    "========================================================================================   \n",
    "The errors which occur because of invalid syntax are called syntax errors.\n",
    "\n",
    "=========================================================================================\n",
    "Eg 1:\n",
    "x = 10\n",
    "if x == 10\n",
    "    print(\"Hello\")\n",
    "\n",
    "SyntaxError: invalid syntax(because we do not include semicolon)\n",
    "\n",
    "======================================================================================    \n",
    "\n",
    "Eg 2:\n",
    "print \"Hello\"\n",
    "\n",
    "SyntaxError: Missing parentheses in call to 'print'\n",
    "    \n",
    "==================================================================\n",
    "Note: Programmer is responsible to correct these syntax errors. Once all syntax errors\n",
    "are corrected then only program execution will be started."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 2) Runtime Errors:\n",
    "    \n",
    "==================================================================================================================\n",
    "Also known as exceptions.\n",
    "While executing the program if something goes wrong because of end user input or\n",
    "programming logic or memory problems etc then we will get Runtime Errors.\n",
    "\n",
    "==================================================================================================================\n",
    "Eg:\n",
    "1) print(10/0)  ZeroDivisionError: division by zero\n",
    "2) print(10/\"ten\")  TypeError: unsupported operand type(s) for /: 'int' and 'str'\n",
    "3) x = int(input(\"Enter Number:\"))\n",
    "print(x)\n",
    "\n",
    "=================================================================================================================\n",
    "D:\\Python_classes>py test.py\n",
    "Enter Number:ten\n",
    "ValueError: invalid literal for int() with base 10: 'ten'\n",
    "        \n",
    "=================================================================================\n",
    "Note: Exception Handling concept applicable for Runtime Errors but not for syntax errors"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# What is Exception?\n",
    "\n",
    "==================================================================================================================\n",
    "An unwanted and unexpected event that disturbs normal flow of program is called exception.\n",
    "\n",
    "=================================================================================================================\n",
    "Eg:\n",
    "\n",
    "ZeroDivisionError\n",
    "TypeError\n",
    "ValueError\n",
    "FileNotFoundError\n",
    "EOFError\n",
    "SleepingError\n",
    "TyrePuncturedError\n",
    "\n",
    "====================================================================\n",
    "It is highly recommended to handle exceptions.The main objective of exception handling is Graceful Termination of the program (i.e we should not block our resources and we\n",
    "should not miss anything)\n",
    "\n",
    "Exception handling does not mean repairing exception. We have to define alternative way\n",
    "to continue rest of the program normally."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Eg:--For example our programming requirement is reading data from remote file locating\n",
    "at London. At runtime if London file is not available then the program should not be\n",
    "terminated abnormally. We have to provide local file to continue rest of the program\n",
    "normally. This way of defining alternative is nothing but exception handling.\n",
    "\n",
    "\n",
    "try:        \n",
    "Read Data from Remote File locating at London.\n",
    "except FileNotFoundError:\n",
    "use local file and continue rest of the program normally\n",
    "\n",
    "============================================================================\n",
    "Q. What is an Exception?\n",
    "Q. What is the purpose of Exception Handling?\n",
    "Q. What is the meaning of Exception Handling?"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Default Exception Handing in Python:\n",
    "\n",
    "==================================================================================================================\n",
    "\n",
    "Every exception in Python is an object. For every exception type the corresponding\n",
    "classes are available.\n",
    "\n",
    "Whevever an exception occurs PVM will create the corresponding exception object\n",
    "and will check for handling code. If handling code is not available then Python\n",
    "interpreter terminates the program abnormally and prints corresponding exception\n",
    "information to the console.\n",
    "\n",
    "The rest of the program won't be executed."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "1) print(\"Hello\")\n",
    "2) print(10/0)\n",
    "3) print(\"Hi\")\n",
    "\n",
    "==================================================================================\n",
    "D:\\Python_classes>py test.py\n",
    "Hello\n",
    "Traceback (most recent call last):\n",
    "File \"test.py\", line 2, in <module>\n",
    "print(10/0)\n",
    "ZeroDivisionError: division by zero"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Python's Exception Hierarchy\n",
    "\n",
    "===============================================================================\n",
    "\n",
    "                             BaseException\n",
    "                                 |\n",
    "                             Exception\n",
    "                                 |\n",
    "      ----------------------------------------------------------------------------                                 |\n",
    "      |                    |                            |                        |\n",
    "      |                    |                            |                        |\n",
    "   Ecception            SystemExit                 GeneratorExit       KeyboardInterrupt\n",
    " \n",
    "   ---------------------------------------------------------------------------------- \n",
    "\n",
    "   Attribute     Arithmetic     EOF      Name      Lookup       OS       Type      Value\n",
    "    Error          Error       Error     Error     Error       Error     Error     Error\n",
    "                                                \n",
    "            |---Zero Division Error              |-Index Error |-File Not Found    \n",
    "            |---FLoating Point Error             |-Key Error   |-Interrupted Error\n",
    "            |---Overflow Error                                 |-Permission Error\n",
    "                                                               |-TImeOut Error\n",
    "\n",
    "===============================================================================\n",
    "\n",
    "Every Exception in Python is a class.\n",
    "All exception classes are child classes of BaseException.i.e every exception class\n",
    "extends BaseException either directly or indirectly. Hence BaseException acts as root\n",
    "for Python Exception Hierarchy.\n",
    "Most of the times being a programmer we have to concentrate Exception and its child\n",
    "classes."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Customized Exception Handling by using try-except:\n",
    "\n",
    "===================================================================================\n",
    "It is highly recommended to handle exceptions.\n",
    "The code which may raise exception is called risky code and we have to take risky code\n",
    "inside try block. The corresponding handling code we have to take inside except block.\n",
    "\n",
    "=================================================================================================================\n",
    "try:\n",
    "   Risky Code\n",
    "except XXX:\n",
    "   Handling code/Alternative Code\n",
    "\n",
    "Without try-except:\n",
    "    \n",
    "1) print(\"stmt-1\")\n",
    "2) print(10/0)   #risky code\n",
    "3) print(\"stmt-3\")\n",
    "\n",
    "==================================================================================================================\n",
    "\n",
    "Output\n",
    "stmt-1\n",
    "ZeroDivisionError: division by zero\n",
    "Abnormal termination/Non-Graceful Termination"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "With try-except:\n",
    "\n",
    "==================================================================================================================\n",
    "print(\"stmt-1\")\n",
    "try:\n",
    "  print(10/0)\n",
    "except ZeroDivisionError:\n",
    "   print(10/2)\n",
    "   print(\"stmt-3\")\n",
    "\n",
    "========================================================================================\n",
    "Output\n",
    "stmt-1\n",
    "5.0\n",
    "stmt-3\n",
    "Normal termination/Graceful Termination"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Control Flow in try-except:\n",
    "\n",
    "=========================================================================================\n",
    "try:\n",
    "    stmt-1\n",
    "    stmt-2\n",
    "    stmt-3\n",
    "except XXX:\n",
    "    stmt-4\n",
    " \n",
    "stmt-5"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "-->Case-1: If there is no exception\n",
    "1,2,3,5 and Normal Termination\n",
    "\n",
    "-->Case-2: If an exception raised at stmt-2 and corresponding except block matched\n",
    "1,4,5 Normal Termination\n",
    "\n",
    "-->Case-3: If an exception rose at stmt-2 and corresponding except block not matched\n",
    "1, Abnormal Termination\n",
    "\n",
    "-->Case-4: If an exception rose at stmt-4 or at stmt-5 then it is always abnormal\n",
    "termination.\n",
    "\n",
    "======================================================================================\n",
    "========================================================================================\n",
    "Conclusions:\n",
    "1) Within the try block if anywhere exception raised then rest of the try block won’t be\n",
    "executed eventhough we handled that exception. Hence we have to take only risky\n",
    "code inside try block and length of the try block should be as less as possible.\n",
    "\n",
    "=================================================================================\n",
    "2) In addition to try block, there may be a chance of raising exceptions inside except and\n",
    "finally blocks also.\n",
    "\n",
    "==========================================================================================\n",
    "3) If any statement which is not part of try block raises an exception then it is always\n",
    "abnormal termination\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "How to Print Exception Information:\n",
    "\n",
    "======================================================================================    \n",
    "try:\n",
    " print(10/0)\n",
    "except ZeroDivisionError as msg:\n",
    "   print(\"exception raised and its description is:\",msg)\n",
    "\n",
    "===========================================================================\n",
    "\n",
    "Output exception raised and its description is: division by zero"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# try with Multiple except Blocks:\n",
    "    \n",
    "================================================================================================================= \n",
    "The way of handling exception is varied from exception to exception.Hence for every exception type a seperate except block we have to provide. i.e try with multiple except\n",
    "blocks is possible and recommended to use.\n",
    "Eg:\n",
    "    \n",
    "    \n",
    "try:\n",
    "\n",
    "-------\n",
    "-------\n",
    "-------\n",
    "except ZeroDivisionError:\n",
    "   perform alternative arithmetic operations\n",
    "except FileNotFoundError:\n",
    "use local file instead of remote file\n",
    "If try with multiple except blocks available then based on raised exception the\n",
    "corresponding except block will be executed.\n",
    "1)try:\n",
    "2)x=int(input(\"Enter First Number: \"))\n",
    "3)y=int(input(\"Enter Second Number: \"))\n",
    "4)print(x/y)\n",
    "5)except ZeroDivisionError :\n",
    "6)   print(\"Can't Divide with Zero\")\n",
    "7)except ValueError:\n",
    "8)  print(\"please provide int value only\")\n",
    "\n",
    "=================================================================================\n",
    "D:\\Python_classes>py test.py\n",
    "Enter First Number: 10\n",
    "Enter Second Number: 2\n",
    "5.0\n",
    "\n",
    "D:\\Python_classes>py test.py\n",
    "Enter First Number: 10\n",
    "Enter Second Number: 0\n",
    "Can't Divide with Zero\n",
    "\n",
    "D:\\Python_classes>py test.py\n",
    "Enter First Number: 10\n",
    "Enter Second Number: ten\n",
    "please provide int value only"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "If try with multiple except blocks available then the order of these except blocks is\n",
    "important .Python interpreter will always consider from top to bottom until matched\n",
    "except block identified.\n",
    "\n",
    "==========================================================\n",
    "1)try:\n",
    "2)x=int(input(\"Enter First Number: \"))\n",
    "3)y=int(input(\"Enter Second Number: \"))\n",
    "4)print(x/y)\n",
    "5)except ArithmeticError :\n",
    "6)  print(\"ArithmeticError\")\n",
    "7)except ZeroDivisionError:\n",
    "8)  print(\"ZeroDivisionError\")\n",
    "\n",
    "Output:-\n",
    "\n",
    "D:\\Python_classes>py test.py\n",
    "Enter First Number: 10\n",
    "Enter Second Number: 0\n",
    "ArithmeticError"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Single except Block that can handle Multiple Exceptions:\n",
    "\n",
    "======================================================================================\n",
    "We can write a single except block that can handle multiple different types of exceptions.\n",
    "except (Exception1,Exception2,exception3,..): OR\n",
    "except (Exception1,Exception2,exception3,..) as msg :\n",
    "Parentheses are mandatory and this group of exceptions internally considered as tuple.\n",
    "\n",
    "====================================================================================\n",
    "1)try:\n",
    "2)   x=int(input(\"Enter First Number: \"))\n",
    "3)   y=int(input(\"Enter Second Number: \"))\n",
    "4)   print(x/y)\n",
    "5)except (ZeroDivisionError,ValueError) as msg:\n",
    "6)    print(\"Plz Provide valid numbers only and problem is: \",msg)\n",
    "\n",
    "==================================================================================\n",
    "D:\\Python_classes>py test.py\n",
    "Enter First Number: 10\n",
    "Enter Second Number: 0\n",
    "Plz Provide valid numbers only and problem is: division by zero\n",
    "\n",
    "=========================================================================================\n",
    "D:\\Python_classes>py test.py\n",
    "Enter First Number: 10\n",
    "Enter Second Number: ten\n",
    "Plz Provide valid numbers only and problem is: invalid literal for int() with b are 10: 'ten'"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Default except Block:\n",
    "\n",
    "=========================================================================================    \n",
    "We can use default except block to handle any type of exceptions.\n",
    "In default except block generally we can print normal error messages.\n",
    "Syntax:\n",
    "    except:\n",
    "        statements\n",
    "        \n",
    "==========================================================================================    \n",
    "try:\n",
    "   x=int(input(\"Enter First Number: \")) \n",
    "   y=int(input(\"Enter Second Number: \"))\n",
    "   print(x/y)\n",
    "\n",
    "except ZeroDivisionError:\n",
    "   print(\"ZeroDivisionError:Can't divide with zero\")\n",
    "\n",
    "except:\n",
    "    print(\"Default Except:Plz provide valid input only\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Output:-\n",
    "    \n",
    "=====================================================================================\n",
    "D:\\Python_classes>py test.py\n",
    "Enter First Number: 10\n",
    "Enter Second Number: 0\n",
    "ZeroDivisionError:Can't divide with zero\n",
    "\n",
    "=========================================================================================  \n",
    "D:\\Python_classes>py test.py\n",
    "Enter First Number: 10\n",
    "Enter Second Number: ten\n",
    "Default Except:Plz provide valid input only\n",
    "    \n",
    "=======================================================================================\n",
    "*** Note: If try with multiple except blocks available then default except block should be\n",
    "last, otherwise we will get SyntaxError.\n",
    "\n",
    "=========================================================================================\n",
    "try:\n",
    " print(10/0)\n",
    "except:\n",
    " print(\"Default Except\")\n",
    "except ZeroDivisionError:\n",
    " print(\"ZeroDivisionError\")\n",
    "\n",
    "SyntaxError: default 'except:' must be last\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Note: The following are various possible combinations of except blocks\n",
    "\n",
    "========================================================================================\n",
    "1) except ZeroDivisionError:\n",
    "2) except ZeroDivisionError as msg:\n",
    "3) except (ZeroDivisionError,ValueError) :\n",
    "4) except (ZeroDivisionError,ValueError) as msg:\n",
    "5) except :\n",
    "\n",
    "=========================================================================================\n",
    "finally Block:\n",
    "\n",
    "=========================================================================================\n",
    "☕ It is not recommended to maintain clean up code(Resource Deallocating Code or\n",
    "Resource Releasing code) inside try block because there is no guarentee for the\n",
    "execution of every statement inside try block always.\n",
    "\n",
    "\n",
    "☕ It is not recommended to maintain clean up code inside except block, because if there\n",
    "is no exception then except block won't be executed.\n",
    "\n",
    "\n",
    "☕ Hence we required some place to maintain clean up code which should be executed\n",
    "always irrespective of whether exception raised or not raised and whether exception\n",
    "handled or not handled. Such type of best place is nothing but finally block.\n",
    "\n",
    "\n",
    "☕ Hence the main purpose of finally block is to maintain clean up code.\n",
    "\n",
    "=============================================================================\n",
    "try:\n",
    "    Risky Code\n",
    "except:\n",
    "    Handling Code\n",
    "finally:\n",
    "    Cleanup code\n",
    "\n",
    "=====================================================================================\n",
    "The speciality of finally block is it will be executed always whether exception raised or\n",
    "not raised and whether exception handled or not handled."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Case-1: If there is no exception\n",
    "\n",
    "======================================================================================\n",
    "try:\n",
    "    print(\"try\")\n",
    "except:\n",
    "    print(\"except\")\n",
    "finally:\n",
    "    print(\"finally\")\n",
    "Output\n",
    "try\n",
    "finally\n",
    "\n",
    "====================================================================================\n",
    "Case-2: If there is an exception raised but handled\n",
    "\n",
    "=======================================================================================\n",
    "try:\n",
    "    print(\"try\")\n",
    "    print(10/0)\n",
    "except ZeroDivisionError:\n",
    "    print(\"except\")\n",
    "finally:\n",
    "    print(\"finally\")\n",
    "\n",
    "======================================================================================\n",
    "Output\n",
    "try\n",
    "except\n",
    "finally\n",
    "\n",
    "=======================================================================================\n",
    "Case-3: If there is an exception raised but not handled\n",
    "    \n",
    "=====================================================================================\n",
    "try:\n",
    "    print(\"try\")\n",
    "    print(10/0)\n",
    "except NameError:\n",
    "    print(\"except\")\n",
    "finally:\n",
    "    print(\"finally\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Output\n",
    "try\n",
    "finally\n",
    "ZeroDivisionError: division by zero(Abnormal Termination)\n",
    "=======================================================================================\n",
    "\n",
    "*** Note: There is only one situation where finally block won't be executed ie whenever\n",
    "we are using os._exit(0) function.\n",
    "Whenever we are using os._exit(0) function then Python Virtual Machine itself will be\n",
    "shutdown.In this particular case finally won't be executed.\n",
    "\n",
    "=====================================================================================\n",
    "imports os\n",
    "try:\n",
    "    print(\"try\")\n",
    "    os._exit(0)\n",
    "except NameError:\n",
    "    print(\"except\")\n",
    "finally:\n",
    "    print(\"finally\")\n",
    "\n",
    "Output: try\n",
    "\n",
    "=========================================================================================\n",
    "Note:\n",
    "os._exit(0)\n",
    "Where 0 represents status code and it indicates normal termination\n",
    "There are multiple status codes are possible"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Control Flow in try-except-finally:\n",
    "\n",
    "==========================================================================================\n",
    "try:\n",
    "    stmt-1\n",
    "    stmt-2\n",
    "    stmt-3\n",
    "except:\n",
    "    stmt-4\n",
    "finally:\n",
    "    stmt-5\n",
    "    stmt-6\n",
    "    \n",
    "========================================================================================\n",
    "Case-1: If there is no exception\n",
    "1,2,3,5,6 Normal Termination\n",
    "\n",
    "===================================================================================\n",
    "Case-2: If an exception raised at stmt2 and the corresponding except block matched\n",
    "1,4,5,6 Normal Termination\n",
    "\n",
    "======================================================================================\n",
    "Case-3: If an exception raised at stmt2 but the corresponding except block not matched\n",
    "1,5 Abnormal Termination\n",
    "\n",
    "=========================================================================================\n",
    "Case-4: If an exception raised at stmt4 then it is always abnormal termination but before\n",
    "that finally block will be executed.\n",
    "\n",
    "=========================================================================================\n",
    "Case-5: If an exception raised at stmt-5 or at stmt-6 then it is always abnormal\n",
    "termination"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Nested try-except-finally Blocks:\n",
    "\n",
    "======================================================================================\n",
    "We can take try-except-finally blocks inside try or except or finally blocks.i.e nesting \n",
    "of try-except-finally is possible.\n",
    "\n",
    "=======================================================================================\n",
    "try:\n",
    "    ----------\n",
    "    ----------\n",
    "    ----------\n",
    "    try:\n",
    "        -------------\n",
    "        --------------\n",
    "        --------------\n",
    "    except:\n",
    "        --------------\n",
    "        --------------\n",
    "        --------------\n",
    "        ------------\n",
    "except:\n",
    "    -----------\n",
    "    -----------\n",
    "    -----------\n",
    "    \n",
    "======================================================================================\n",
    "General Risky code we have to take inside outer try block and too much risky code we\n",
    "have to take inside inner try block. Inside Inner try block if an exception raised then inner except block is responsible to handle. If it is unable to handle then outer except block is responsible to handle\n",
    "\n",
    "==============================================================================\n",
    "\n",
    "try:\n",
    "    print(\"outer try block\")\n",
    "    try:\n",
    "        print(\"Inner try block\")\n",
    "        print(10/0)\n",
    "    except ZeroDivisionError:\n",
    "        print(\"Inner except block\")\n",
    "    finally:\n",
    "        print(\"Inner finally block\")\n",
    "except:\n",
    "    print(\"outer except block\")\n",
    "finally:\n",
    "    print(\"outer finally block\")\n",
    "\n",
    "===================================================================================\n",
    "Output\n",
    "\n",
    "outer try block\n",
    "Inner try block\n",
    "Inner except block\n",
    "Inner finally block\n",
    "outer finally block"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Control Flow in nested try-except-finally:\n",
    "\n",
    "========================================================================================    \n",
    "try: \n",
    "    stmt-1\n",
    "    stmt-2\n",
    "    stmt-3\n",
    "    try:\n",
    "        stmt-4\n",
    "        stmt-5\n",
    "        stmt-6\n",
    "    except X:\n",
    "        stmt-7\n",
    "    finally:\n",
    "        stmt-8\n",
    "        stmt-9\n",
    "except Y:\n",
    "    stmt-10\n",
    "finally:\n",
    "    stmt-11\n",
    "stmt-12"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Case-1: If there is no exception\n",
    "1,2,3,4,5,6,8,9,11,12 Normal Termination\n",
    "\n",
    "=======================================================================================\n",
    "Case-2: If an exception raised at stmt-2 and the corresponding except block matched\n",
    "1,10,11,12 Normal Termination\n",
    "\n",
    "========================================================================================\n",
    "Case-3: If an exceptiion raised at stmt-2 and the corresponding except block not matched\n",
    "1,11,Abnormal Termination\n",
    "\n",
    "=======================================================================================\n",
    "Case-4: If an exception raised at stmt-5 and inner except block matched\n",
    "1,2,3,4,7,8,9,11,12 Normal Termination\n",
    "\n",
    "=======================================================================================\n",
    "Case-5: If an exception raised at stmt-5 and inner except block not matched but outer\n",
    "except block matched\n",
    "1,2,3,4,8,10,11,12,Normal Termination\n",
    "\n",
    "========================================================================================\n",
    "Case-6: If an exception raised at stmt-5 and both inner and outer except blocks are not\n",
    "matched\n",
    "1,2,3,4,8,11,Abnormal Termination\n",
    "\n",
    "=======================================================================================\n",
    "Case-7: If an exception raised at stmt-7 and corresponding except block matched\n",
    "1,2,3,.,.,.,8,10,11,12,Normal Termination\n",
    "\n",
    "======================================================================================\n",
    "Case-8: If an exception raised at stmt-7 and corresponding except block not matched\n",
    "1,2,3,.,.,.,8,11,Abnormal Termination\n",
    "\n",
    "=======================================================================================\n",
    "Case-9: If an exception raised at stmt-8 and corresponding except block matched\n",
    "1,2,3,.,.,.,.,10,11,12 Normal Termination\n",
    "\n",
    "=====================================================================================\n",
    "Case-10: If an exception raised at stmt-8 and corresponding except block not matched\n",
    "1,2,3,.,.,.,.,11,Abnormal Termination\n",
    "\n",
    "=====================================================================================\n",
    "Case-11: If an exception raised at stmt-9 and corresponding except block matched\n",
    "1,2,3,.,.,.,.,8,10,11,12,Normal Termination\n",
    "\n",
    "==================================================================================\n",
    "Case-12: If an exception raised at stmt-9 and corresponding except block not matched\n",
    "1,2,3,.,.,.,.,8,11,Abnormal Termination\n",
    "\n",
    "===================================================================================\n",
    "Case-13: If an exception raised at stmt-10 then it is always abonormal termination but\n",
    "before abnormal termination finally block(stmt-11) will be executed.\n",
    "\n",
    "=====================================================================================\n",
    "Case-14: If an exception raised at stmt-11 or stmt-12 then it is always abnormal\n",
    "termination.\n",
    "\n",
    "======================================================================================\n",
    "\n",
    "Note: If the control entered into try block then compulsary finally block will be executed.\n",
    "If the control not entered into try block then finally block won't be execut"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "else Block with try-except-finally:\n",
    "    \n",
    "========================================================================================\n",
    "We can use else block with try-except-finally blocks.\n",
    "else block will be executed if and only if there are no exceptions inside try block.\n",
    "\n",
    "======================================================================================\n",
    "try:\n",
    "    Risky Code\n",
    "except:\n",
    "    will be executed if exception inside try\n",
    "else:\n",
    "    will be executed if there is no exception inside try\n",
    "finally:\n",
    "    will be executed whether exception raised or not raised and handled or not\n",
    "    handled\n",
    "\n",
    "========================================================================================\n",
    "Eg:\n",
    "    \n",
    "===================================================================================\n",
    "try:\n",
    "    print(\"try\")\n",
    "    print(10/0) -> 1\n",
    "except:\n",
    "    print(\"except\")\n",
    "else:\n",
    "    print(\"else\")\n",
    "finally:\n",
    "    print(\"finally\")\n",
    "\n",
    "========================================================================================    \n",
    "If we comment line-1 then else block will be executed b'z there is no exception inside try.\n",
    "In this case the output is:\n",
    "try\n",
    "else\n",
    "finally\n",
    "\n",
    "================================================================================\n",
    "If we are not commenting line-1 then else block won't be executed b'z there is exception\n",
    "inside try block. In this case output is:\n",
    "try\n",
    "except\n",
    "finall"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Various possible Combinations of try-except-else-finally:\n",
    "\n",
    "=================================================================================\n",
    "1) Whenever we are writing try block, compulsory we should write except or finally\n",
    "block.i.e without except or finally block we cannot write try block.\n",
    "\n",
    "===================================================================================\n",
    "2) Wheneever we are writing except block, compulsory we should write try block. i.e\n",
    "except without try is always invalid.\n",
    "\n",
    "====================================================================================\n",
    "3) Whenever we are writing finally block, compulsory we should write try block. i.e\n",
    "finally without try is always invalid.\n",
    "\n",
    "====================================================================================\n",
    "4) We can write multiple except blocks for the same try,but we cannot write multiple\n",
    "finally blocks for the same try\n",
    "\n",
    "===================================================================================\n",
    "5) Whenever we are writing else block compulsory except block should be there. i.e\n",
    "without except we cannot write else block.\n",
    "\n",
    "==================================================================================\n",
    "6) In try-except-else-finally order is important.\n",
    "\n",
    "==================================================================================\n",
    "7) We can define try-except-else-finally inside try, except, else and finally blocks. i.e\n",
    "nesting of try-except-else-finally is always possible.\n",
    "\n",
    "======================================================================================="
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "##1.\n",
    "try:\n",
    "    print(\"try\")\n",
    "    \n",
    "#Note:-we can't take only try block try always come with except block"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#2.\n",
    "except:\n",
    "    print(\"Hello\")\n",
    "#"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#3.\n",
    "else:\n",
    "    print(\"Hello\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#4.\n",
    "finally:\n",
    "    print(\"Hello\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#5.\n",
    "try:\n",
    "    print(\"try\")\n",
    "except:\n",
    "    print(\"except\")\n",
    "    \n",
    "Note:-"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#6,\n",
    "try:\n",
    "    print(\"try\")\n",
    "finally:\n",
    "    print(\"finally\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#7\n",
    "try:\n",
    "    print(\"try\")\n",
    "except:\n",
    "    print(\"except\")\n",
    "else:\n",
    "    print(\"else\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#8\n",
    "\n",
    "try:\n",
    "    print(\"try\")\n",
    "else:\n",
    "    print(\"else\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#9.\n",
    "try:\n",
    "    print(\"try\")\n",
    "else:\n",
    "    print(\"else\")\n",
    "finally:\n",
    "    print(\"finally\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#10.\n",
    "try:\n",
    "    print(\"try\")\n",
    "except XXX:\n",
    "    print(\"except-1\")\n",
    "except YYY:\n",
    "    print(\"except-2\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#11.\n",
    "\n",
    "try:\n",
    "    print(\"try\")\n",
    "except :\n",
    "    print(\"except-1\")\n",
    "else:\n",
    "    print(\"else\")\n",
    "else:\n",
    "    print(\"else\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#12\n",
    "try:\n",
    "    print(\"try\")\n",
    "except :\n",
    "    print(\"except-1\")\n",
    "finally:\n",
    "    print(\"finally\")\n",
    "finally:\n",
    "    print(\"finally\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#13\n",
    "try:\n",
    "    print(\"try\")\n",
    "    print(\"Hello\")\n",
    "except:\n",
    "    print(\"except\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#14\n",
    "try:\n",
    "    print(\"try\")\n",
    "except:\n",
    "    print(\"except\")\n",
    "    print(\"Hello\")\n",
    "except:\n",
    "    print(\"except\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#15\n",
    "try:\n",
    "    print(\"try\")\n",
    "except:\n",
    "    print(\"except\")\n",
    "    print(\"Hello\")\n",
    "finally:\n",
    "    print(\"finally\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#16\n",
    "try:\n",
    "    print(\"try\")\n",
    "except:\n",
    "    print(\"except\")\n",
    "    print(\"Hello\")\n",
    "else:\n",
    "    print(\"else\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#17\n",
    "try:\n",
    "    print(\"try\")\n",
    "except:\n",
    "    print(\"except\")\n",
    "try:\n",
    "    print(\"try\")\n",
    "except:\n",
    "    print(\"except\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#18\n",
    "try:\n",
    "    print(\"try\")\n",
    "except:\n",
    "    print(\"except\")\n",
    "try:\n",
    "    print(\"try\")\n",
    "finally:\n",
    "    print(\"finally\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#19\n",
    "try:\n",
    "    print(\"try\")\n",
    "except:\n",
    "    print(\"except\")\n",
    "if 10>20:\n",
    "    print(\"if\")\n",
    "else:\n",
    "    print(\"else\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#20\n",
    "try:\n",
    "    print(\"try\")\n",
    "    try:\n",
    "        print(\"inner try\")\n",
    "    except:\n",
    "        print(\"inner except block\")\n",
    "    finally:\n",
    "        print(\"inner finally block\")\n",
    "except:\n",
    "print(\"except\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#21\n",
    "try:\n",
    "    print(\"try\")\n",
    "except:\n",
    "    print(\"except\")\n",
    "    try:\n",
    "        print(\"inner try\")\n",
    "    except:\n",
    "        print(\"inner except block\")\n",
    "    finally:\n",
    "        print(\"inner finally block\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#22\n",
    "try:\n",
    "    print(\"try\")\n",
    "except:\n",
    "    print(\"except\")\n",
    "finally:\n",
    "    try:\n",
    "        print(\"inner try\")\n",
    "    except:\n",
    "        print(\"inner except block\")\n",
    "    finally:\n",
    "        print(\"inner finally block\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#23\n",
    "try:\n",
    "    print(\"try\")\n",
    "except:\n",
    "    print(\"except\")\n",
    "try:\n",
    "    print(\"try\")\n",
    "else:\n",
    "    print(\"else\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#24\n",
    "try:\n",
    "    print(\"try\")\n",
    "    try:\n",
    "        print(\"inner try\")\n",
    "except:\n",
    "    print(\"except)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#25\n",
    "try:\n",
    "    print(\"try\")\n",
    "else:\n",
    "    print(\"else\")\n",
    "except:\n",
    "    print(\"except\")\n",
    "finally:\n",
    "    print(\"finally\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Types of Exceptions:\n",
    "In Python there are 2 types of exceptions are possible.\n",
    "1) Predefined Exceptions\n",
    "2) User Definded Exceptions\n",
    "\n",
    "=====================================================================================\n",
    "1) Predefined Exceptions:\n",
    "\n",
    "====================================================================================\n",
    "Also known as inbuilt exceptions.\n",
    "The exceptions which are raised automatically by Python virtual machine whenver a\n",
    "particular event occurs are called pre defined exceptions.\n",
    "\n",
    "Eg 1: Whenever we are trying to perform Division by zero, automatically Python will\n",
    "raise ZeroDivisionError.\n",
    "print(10/0)\n",
    "\n",
    "=======================================================================================\n",
    "Eg 2: Whenever we are trying to convert input value to int type and if input value is\n",
    "not int value then Python will raise ValueError automatically\n",
    "x=int(\"ten\")  ValueError\n",
    "\n",
    "==================================================================================\n",
    "2) User Defined Exceptions:\n",
    "Also known as Customized Exceptions or Programatic Exceptions\n",
    "Some time we have to define and raise exceptions explicitly to indicate that something\n",
    "goes wrong, such type of exceptions are called User Defined Exceptions or Customized\n",
    "Exceptions\n",
    "\n",
    "====================================================================================\n",
    "Programmer is responsible to define these exceptions and Python not having any idea\n",
    "about these. Hence we have to raise explicitly based on our requirement by using\n",
    "\"raise\" keyword.\n",
    "Eg:\n",
    "InSufficientFundsException\n",
    "InvalidInputException\n",
    "TooYoungException\n",
    "TooOldException"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# How to Define and Raise Customized Exceptions:\n",
    "\n",
    "=======================================================================================    \n",
    "Every exception in Python is a class that extends Exception class either directly or\n",
    "indirectly.\n",
    "Syntax:\n",
    "\n",
    "=======================================================================================\n",
    "class classname(predefined exception class name):\n",
    "    def __init__(self,arg):\n",
    "        self.msg=arg\n",
    "class TooYoungException(Exception):\n",
    "    def __init__(self,arg):\n",
    "        self.msg=arg\n",
    "        \n",
    "TooYoungException is our class name which is the child class of Exception\n",
    "\n",
    "=====================================================================================\n",
    "We can raise exception by using raise keyword as follows\n",
    "raise TooYoungException(\"message\")\n",
    "\n",
    "======================================================================================\n",
    "class TooYoungException(Exception):\n",
    "    def __init__(self,arg):\n",
    "        self.msg=arg\n",
    "class TooOldException(Exception):\n",
    "    def __init__(self,arg):\n",
    "        self.msg=arg\n",
    "        age=int(input(\"Enter Age:\"))\n",
    "         if age>60:\n",
    "            raise TooYoungException(\" Plz wait some more time you will get best match                         soon!!!\" )\n",
    "         elif age<18:\n",
    "             raise TooOldException(\"Your age already crossed marriage age...no chance of\n",
    "                    getting marriage\")\n",
    "         else:\n",
    "            print(\"You will get match details soon by email!!!\")\n",
    "\n",
    "==========================================================================================\n",
    "D:\\Python_classes>py test.py\n",
    "Enter Age:90\n",
    "__main__.TooYoungException: Plz wait some more time you will get best match soon!!!\n",
    "\n",
    "=====================================================================================\n",
    "D:\\Python_classes>py test.py\n",
    "Enter Age:12\n",
    "__main__.TooOldException: Your age already crossed marriage age...no chance of g\n",
    "etting marriage\n",
    "D:\\Python_classes>py test.py\n",
    "Enter Age:27\n",
    "You will get match details soon by email!!!\n",
    "Note: raise keyword is best suitable for customized exceptions but not for pre defined\n",
    "except"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
